name: Example workflow for Python using Snyk - CODE test with GH integration
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.7@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Build, tag, and push docker image to Amazon ECR
        run: 
          pip install -r requirements.txt
          snyk code test --sarif-file-codesarif.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      - name: uppload code sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codesarif.sarif
